#!/bin/bash

STYLUS="Wacom Intuos BT S Pen stylus"
PAD="Wacom Intuos BT S Pad pad"
ERASER="Wacom Intuos BT S Pen eraser"
CURSOR="Wacom Intuos BT S Pen cursor"
MONITOR="DVI-I-1-1"

xrandr --output DVI-I-1-1 --rotate left
xrandr --output DVI-I-1-1 --right-of eDP-1
xrandr --output DVI-I-1-1 --pos 1920x0
xrandr --output DVI-I-1-1 --pos 1920x-740

# Run default Wacom settings

init-wacom

# Map devices to output

xsetwacom --set $STYLUS MapToOutput $MONITOR
xsetwacom --set $PAD MapToOutput $MONITOR
xsetwacom --set $ERASER MapToOutput $MONITOR
xsetwacom --set $CURSOR MapToOutput $MONITOR

# Rotate pad counterclockwise 90°

xsetwacom --set $STYLUS rotate cw
xsetwacom --set $PAD rotate cw
xsetwacom --set $ERASER rotate cw
xsetwacom --set $CURSOR rotate cw
